GET https://api.druwa.site/dramas/73
Accept: application/json

###

POST https://api.druwa.site/dramas
Accept: application/json
Content-Type: application/json
Authorization: Bearer DRUWA_TEST_TOKEN

{
  "title": "연애플레이리스트 시즌 1",
  "summary" : "새학기 시작을 풋풋한 대학 청춘 멜로와 함께",
  "productionCompany" : "플레이리스트"
}

###
